FROM openjdk:8u191-jre-alpine
MAINTAINER sujuanliu<sujuanliu@gmail.com>

ARG KAFKA_VERSION=2.11-1.1.0

ADD kafka.tgz /opt/
ADD start-kafka.sh /opt/
WORKDIR /opt/kafka_2.11-1.1.0
RUN chmod +x /opt/start-kafka.sh
VOLUME /tmp/kafka-logs
ENV KAFKA_BROKER_ID 0
ENV KAFKA_ZOOKEEPER_CONNECT zk
ENV KAFKA_LISTENERS PLAINTEXT://:9092
ENV KAFKA_PORT 9092
ENV KAFKA_NUM_PARTITIONS 2
ENV KAFKA_NUM_NETWORK_THREADS 5
ENV KAFKA_NUM_IO_THREADS 8
ENV KAFKA_LOG_RETENTION_HOURS 72
ENV KAFKA_LOG_DIRS /tmp/kafka-logs
ENV KAFKA_LOG_RETENTION_BYTES 10737418240
ENV KAFKA_LOG_SEGMENT_BYTES 1073741824
ENV KAFKA_LOG_FLUSH_INTERVAL_MESSAGES 10000
ENV KAFKA_LOG_FLUSH_INTERVAL_MS 1000
ENV KAFKA_DEFAULT_REPLICATION_FACTOR 2
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR 3
ENV KAFKA_TRANSACTION.STATE_LOG_REPLICATION_FACTOR 3
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR 3

CMD ["sh","/opt/start-kafka.sh"]
