version: '3'

services:
  kafka:
    image: kafka:2.11-1.1.0
    hostname: xxx.xxx.xx.xxx
    ports:
     - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
      - /data/logs/kafka:/tmp/kafka-logs
